# 选择镜像，我这里使用的是之前自己安装的ubuntu:20.04镜像
FROM ubuntu:20.04 
# 创建者信息
MAINTAINER chivas_regal
# run 运行后面的命令，在镜像的root/projects文件夹中创建一codingCloudDB文件夹
RUN mkdir /root/projects/codingCloudDB
# add 添加当前文件夹下到上面创建的文件夹
ADD ./ root/projects/codingCloudDB

